grexco/grexco/urls.py
from django.contrib import admin
from django.contrib.auth.views import logout
from django.urls import include, path

from usuarios.views import LoginView


urlpatterns = [
    path('', include('landing.urls')),
    path('a/', include('administracion.urls')),
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout, {'next_page': '/'}, name='logout'),
    path('usuarios/', include('usuarios.urls')),
    path('soporte/', include('soporte.urls')),
]

grexco/soporte/urls.py
from django.urls import path

from . import views

app_name = 'soporte'

urlpatterns = [
    path('', views.HomeSoporteView.as_view(), name='home_soporte'),
    path(
        'incidentes/listado/',
        views.ListadoIncidentesView.as_view(),
        name='incidentes_listado'
    ),
    path(
        'incidentes/consulta/<int:codigo>',
        views.DetalleIncidentesView.as_view(),
        name='incidentes_consulta'
    ),
    path(
        'consulta/usuarios/',
        views.ConsultaUsuariosSoporteView.as_view(),
        name='usuarios'
    ),
    path(
        'asigna/incidentes/soporte/',
        views.AsignaIncidentesSoporteView.as_view(),
        name='asigna_soporte'
    ),
]

grexco/soporte/models.py
"""Modelos para la aplicación de Soporte."""

from django.contrib.auth.models import User
from django.db import models

from administracion.models import ubicacion_archivos
from usuarios.models import Incidentes
from tecnologia.models import Cambios


# Create your models here.


class ResultadosPruebas(models.Model):
    codigo = models.CharField(primary_key=True, max_length=1)
    descripcion = models.CharField(max_length=20)

    def __str__(self):
        return '{}'.format(self.descripcion)


class Pruebas(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    cambio = models.ForeignKey(
        Cambios, on_delete=models.PROTECT, related_name='pruebas')
    fecha = models.DateTimeField(auto_now_add=True)
    resultado = models.ForeignKey(
        ResultadosPruebas, on_delete=models.PROTECT, related_name='pruebas')

    def __str__(self):
        return '{}:{}'.format(self.id, self.resultado)


class ArchivosPruebas(models.Model):
    prueba = models.ForeignKey(
        Pruebas, on_delete=models.PROTECT, related_name='adjuntos')
    archivo = models.FileField(
        storage=ubicacion_archivos, upload_to='pruebas/{}'.format(prueba))

    def __str__(self):
        return '{}'.format(self.archivo)


class NotasSoporte(models.Model):
    incidente = models.ForeignKey(
        Incidentes, on_delete=models.PROTECT)
    usuario = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name='usuario_soporte')
    fecha = models.DateTimeField(auto_now_add=True)
    nota = models.TextField(null=True, blank=True)


class NotasTecnologia(models.Model):
    incidente = models.ForeignKey(
        Incidentes, on_delete=models.PROTECT)
    usuario = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name='usuario_tecnologia')
    fecha = models.DateTimeField(auto_now_add=True)
    nota = models.TextField(null=True, blank=True)

grexco/soporte/views.py
"""Logica para manejar los procesos de Soporte."""

import json

from datetime import datetime
from datetime import timedelta

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.db import transaction
from django.http import JsonResponse
from django.views.generic import TemplateView, View

from administracion.models import TiemposRespuesta
from usuarios.models import Adjuntos
from usuarios.models import EstadosIncidentes
from usuarios.models import Incidentes
from usuarios.models import MovimientosIncidentes
from usuarios.models import UsuariosSoporteIncidentes

# Función para calcular el tiempo de respuesta
from .fecha_respuesta import f_respuesta



class HomeSoporteView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    """
    Home para los clientes de Grexco.

        :url    :soporte/
    """

    login_url = 'usuarios:login'
    template_name = 'soporte/home.html'

    def test_func(self):
        """
        Retringe el acceso de usuarios.

        Solo permite el acceso a los usuarios:
            - Administrador
            - Soporte
        """
        tipo = self.request.user.usuariosgrexco.tipo
        return tipo == 'A' or tipo == 'S'


class ListadoIncidentesView(LoginRequiredMixin, UserPassesTestMixin, View):
    """
    Retorna un listado de todos los incidentes creados.

        :url :soporte/incidentes/listado/
    """

    login_url = 'usuarios:login'

    def test_func(self):
        """
        Retringe el acceso de usuarios.

        Solo permite el acceso a los usuarios:
            - Administrador
            - Soporte
        """
        tipo = self.request.user.usuariosgrexco.tipo
        return tipo == 'A' or tipo == 'S'

    def get(self, request):
        """docstring."""
        usuario = self.request.user
        coordinador = self.request.user.usuariosgrexco.es_coordinador

        if coordinador is True:
            qry_incidentes = (
                Incidentes.objects
                          .all()
                          .values(
                              'codigo',
                              'titulo',
                              'aplicacion__nombre',
                              'estado__descripcion',
                              'fecha_creacion',
                              'usuario__usuariosgrexco__empresa__nombre'
                          )
            )
            incidentes = []
            for incidente in qry_incidentes:
                incidente['fecha_creacion'] = datetime.strftime(
                    incidente['fecha_creacion'], format='%Y-%m-%d')
                incidentes.append(incidente)

            return JsonResponse({'incidentes': incidentes}, status=200)
        else:
            print('usuario no coordinador')
            qry_incidentes = (
                UsuariosSoporteIncidentes.objects
                                         .filter(usuario=usuario,
                                                 incidente__estado='S')
                                         .values(
                                             'incidente__codigo',
                                             'incidente__titulo',
                                             'incidente__aplicacion__nombre',
                                             'incidente__estado__descripcion',
                                             'incidente__fecha_creacion',
                                             'usuario__usuariosgrexco__empresa__nombre'
                                         )
            )
            incidentes = []
            for incidente in qry_incidentes:
                incidentes.append(incidente)
            return JsonResponse({'incidentes': incidentes}, status=200)


class DetalleIncidentesView(
        LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    """Template para consulta un incidente."""

    login_url = 'usuarios:login'
    template_name = 'soporte/detalle_incidente.html'

    def test_func(self):
        """
        Retringe el acceso de usuarios.

        Solo permite el acceso a los usuarios:
            - Administrador
            - Soporte
        """
        tipo = self.request.user.usuariosgrexco.tipo
        return tipo == 'A' or tipo == 'S'

    def get_context_data(self, *args, **kwargs):
        """Envia la información del Incidente consultado."""
        codigo = kwargs['codigo']
        incidente = Incidentes.objects.get(codigo=codigo)

        adjuntos = Adjuntos.objects.filter(incidente=incidente)
        return {'codigo': codigo, 'incidente': incidente, 'adjuntos': adjuntos}


class ConsultaUsuariosSoporteView(
        LoginRequiredMixin, UserPassesTestMixin, View):
    """Retorna un listado Json con los nombres de usuario de los empleados
    de soporte ACTIVOS.
    """

    login_url = 'usuarios:login'

    def test_func(self):
        """
        Retringe el acceso de usuarios.

        Solo permite el acceso a los usuarios:
            - Administrador
            - Soporte
            - Tecnologia
        """
        tipo = self.request.user.usuariosgrexco.tipo
        return tipo == 'A' or tipo == 'S' or tipo == 'T'

    def get(self, request):
        usuarios = list(User.objects.filter(
            is_active=True, usuariosgrexco__tipo='S').values('username'))
        return JsonResponse({'usuarios': usuarios}, status=200)


class AsignaIncidentesSoporteView(
        LoginRequiredMixin, UserPassesTestMixin, View):
    """Vista para asignar incidentes a los empleados de Soporte."""

    login_url = 'usuarios:login'

    def test_func(self):
        """
        Restringe el acceso de usuarios.

        Solo permite el acceso a los usuarios:
            - Administrador
            - Soporte
            - Tecnologia
        """
        tipo = self.request.user.usuariosgrexco.tipo
        es_coordinador = self.request.user.usuariosgrexco.es_coordinador

        if tipo == 'A':
            return True
        elif tipo == 'S' and es_coordinador is True:
            return True
        else:
            return False

    def get(self, request):
        return JsonResponse({'ok': 'ok'}, status=200)

    def post(self, request, *args, **kwargs):
        """Recibe el codigo del usuario y de incidente para asignar el
        incidente al usuario."""
        data = json.loads(request.body.decode('utf-8'))
        cod_usuario = data['usuario']
        cod_incidente = data['incidente']
        cod_prioridad = data['prioridad']
        estado = EstadosIncidentes.objects.get(codigo='S')

        with transaction.atomic():
            # Verifica que el incidente no tenga usuario se Soporte asignado.
            qry_usuario_soporte = UsuariosSoporteIncidentes.objects.filter(
                incidente=cod_incidente)
            if qry_usuario_soporte:
                return JsonResponse(
                    {'error': 'El incidente ya tiene un usuario asignado'},
                    status=400)

            # Asigna el Usuario al Incidente.
            usr_soporte = User.objects.get(username=cod_usuario)
            incidente = Incidentes.objects.get(codigo=cod_incidente)
            u = UsuariosSoporteIncidentes(
                usuario=usr_soporte, incidente=incidente)
            try:
                u.save()
            except Exception as e:
                return JsonResponse({'error': e}, status=400)

            print('usuarios incidente')

            # Guarda los movimientos del Incidente.
            usr_coordinador = self.request.user
            movimiento = MovimientosIncidentes(
                incidente=incidente,
                estado=estado,
                responsable=usr_coordinador)
            try:
                movimiento.save()
            except Exception as e:
                return JsonResponse({'error': e}, status=400)
            # Cambia el estado del Incidente.
            incidente.estado = estado
            try:
                incidente.save()
            except Exception as e:
                return JsonResponse({'error': e}, status=400)

            # Calcula la fecha de respuesta
            """
            empresa = incidente.usuario.usuariosgrexco.empresa
            qry_tiempo_respuesta = TiemposRespuesta.objects.get(
                empresa=empresa, prioridad=cod_prioridad)
            tiempo_respuesta = timedelta(hours=qry_tiempo_respuesta.tiempo)
            print(tiempo_respuesta)
            fecha = incidente.fecha_creacion
            print(fecha)
            """
            fecha = incidente.fecha_creacion
            tiempo = timedelta(hours=8)
            fecha_respuesta = f_respuesta(incidente, tiempo, fecha)
            print('fecha_respuesta', fecha_respuesta)

            # Si NO hay ningún error.
            return JsonResponse(
                {'ok': 'Se asignó el incidente correctamente'}, status=200)

grexco/soporte/templates/soporte/alertas.html
<!-- ALERTAS -->
<div class="row">
  <div class="col">
    <div style="width: 100%;">
                   
      <!-- Alerta ok -->
      <div class="alert alert-success alert-dismissible fade show p-1" id="alertaOk" style="display: none;">
        <div class="row">
          <div class="col-10" id="alertaOkMensaje">
          </div>
          <div class="col-2">
            <button type="button" class="close mr-3 p-0 btnCerrarAlerta">
              <i class="material-icons">close</i>
            </button>
          </div>
        </div>
      </div>

      <!-- Alerta error -->
      <div class="alert alert-danger alert-dismissible fade show p-1"
           id="alertaError"
           style="display: none;">
        <div class="row">
          <div class="col-10" id="alertaErrorMensaje">
          </div>
          <div class="col-2">
            <button type="button" class="close mr-3 p-0 btnCerrarAlerta">
              <i class="material-icons">close</i>
            </button>
          </div>  
        </div>
      </div>
    
    </div> 
  </div>
</div>
<!-- FIN ALERTAS -->

grexco/soporte/templates/soporte/base_contenido.html
{% extends './base_home.html' %}

{% block contenedor %}
<div class="container">
	<div class="row">
		<div class="col">
			<div class="row mt-2">
				{% block titulo_contenido %}
				{% endblock %}
			</div>
			<div class="row">
				<div class="rounded bg-light w-100 p-2">
					{% block barra_herramientas %}
					{% endblock %}
				</div>
			</div>
			<div class="row mt-3">
				{% block contenido %}
				{% endblock %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

grexco/soporte/templates/soporte/base_home.html
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block title %} {% endblock %}
	</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% load static %}

	<!-- Jquery -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	<!-- CSS DataTables -->
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/b-1.5.2/b-print-1.5.2/sc-1.5.0/sl-1.2.6/datatables.min.css"/>

	<!-- JS DataTables --> 
	<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/b-1.5.2/b-print-1.5.2/sc-1.5.0/sl-1.2.6/datatables.min.js"></script>

	<!-- Bootstrap -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="{% static '/bootstrap-4.1.1/dist/js/bootstrap.min.js' %}"></script>
	
	<!-- CSS Bootstrap -->
	<link rel="stylesheet" href="{% static '/bootstrap-4.1.1/dist/css/bootstrap.min.css' %}">
		
	<!-- Google Icons -->
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

	<!-- Font awesome -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

	<!-- CSS -->
	<link rel="stylesheet" href="{% static '/css/base.css' %}">

	{% block css %}

	{% endblock %}
	
</head>
<body style="font-size: .875rem; font-family: 'Roboto', sans-serif;">
	<i id="es_coordinador" class="d-none">{{ request.user.usuariosgrexco.es_coordinador }}</i>
	<!-- Top nav -->
	<nav class="nav bg-primary sticky-top clearfix shadow" style="width: 100%; height: 40px;">
		<div class="col">
			<a href="#" class="navbar-brand" style="color: white; font-size: 20px;">GREXCO</a>
		</div>
		<div class="col">
			<!-- Opciones de usuario y cerrar sesión -->
			<div class="dropdown">
				<button class="btn btn-sm btn-primary float-right p-0" data-toggle="dropdown">
					<i class="material-icons person md-30">person</i>
				</button>
				<div class="dropdown-menu p-0" style="font-size: 14px;">
					<a href="#" class="dropdown-item p-1 text-center"><b>Usuario/</b> {{ request.user.username }}</a>
					<i id="nitEmpresa" class="d-none">{{ request.user.usuariosgrexco.empresa.nit }}</i>
					<div class="dropdown-divider m-1"></div>
					<a href="{% url 'logout' %}"
						 class="dropdown-item p-1 text-center">
						<i class="material-icons align-middle md-21">exit_to_app</i> 
						Cerrar sesión
					</a>
				</div>
			</div>
		</div>
	</nav>
	<!-- Fin top nav -->

  <div class="container-fluid">
    <div class="row">
			
			<!-- Sidebar -->
      <nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="sidebar-sticky mb-3">
        	
        	<!-- Acordión Incidentes -->
        	<div class="accordion m-1 mt-2">
        		<button class="btn btn-sm btn-block btn-light text-left text-primary"
        						type="button" 
        						data-toggle="collapse" 
        						data-target="#collapseIncidentes" 
        						style="font-size: 15px;">
        			Incidentes <span class="badge badge-danger ml-2">1</span>
        		</button>
        		<div id="collapseIncidentes" class="collapse pl-4">
							<nav class="nav flex-column">
								{% if request.user.usuariosgrexco.es_coordinador %}
									<a href="{% url 'soporte:home_soporte' %}" class="nav-link p-1">Consultar</a>
								{% endif %}
								<a href="{% url 'soporte:home_soporte' %}" class="nav-link p-1">Asignados</a>
							</nav>
        		</div>
        	</div>

        	<!-- Acordión Cambios -->
        	<div class="accordion m-1 mt-2">
        		<button class="btn btn-sm btn-block btn-light text-left text-primary"
        						type="button" 
        						data-toggle="collapse" 
        						data-target="#collapseCambios" 
        						style="font-size: 15px;">
        			Cambios <span class="badge badge-danger ml-2">1</span>
        		</button>
        		<div id="collapseCambios" class="collapse pl-4">
							<nav class="nav flex-column">
								{% if request.user.usuariosgrexco.es_coordinador %}
									<a href="{% url 'soporte:home_soporte' %}" class="nav-link p-1">Consultar</a>
								{% endif %}
								<a href="{% url 'soporte:home_soporte' %}" class="nav-link p-1">Asignados</a>
							</nav>
        		</div>
        	</div>

        </div>
      </nav>
      <!-- Fin sidebar -->

			<!-- Contenido -->
      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
      	{% block contenedor %}
      	{% endblock %}
      </main>
      <!-- Fin contenido -->
    </div>
  </div>
	
	<script src="{% static '/js/urls.js' %}"></script>

	{% block js %}

	{% endblock %}

</body>
</html>

grexco/soporte/templates/soporte/detalle_incidente.html
{% extends './base_contenido.html' %}

{% load static %}

{% block title %}
	Incidente: {{ codigo }}
{% endblock %}

{% block css %}
	<link rel="stylesheet" href="{% static '/css/detalle_incidente.css' %}">
{% endblock%}

{% block titulo_contenido %}
	<h4>Incidente: {{ codigo }}</h4>
{% endblock %}

{% block barra_herramientas %}
	{% if incidente.estado.descripcion == 'Creado' %}
		<button class="btn btn-sm btn-info ml-1" id="btnConsultar" data-toggle="modal" data-target="#modalSelUsuario">
		  <i class="material-icons md-21 align-middle mr-1">share</i> Asignar
		</button>	
	{% endif %}
	<button class="btn btn-sm ml-1">
		<i></i>P
	</button>
{% endblock %}

{% block contenido %}
{% csrf_token %}
<i id="codigo" class="d-none">{{ codigo }}</i>

<!-- Datos del Incidente -->
{% if incidente.estado.descripcion == 'Creado' %}
	<div class="container-fluid">			
		<div class="row">
			<div class="col">
				<div class="row">
					<div class="col-sm-2">
						<p class="p-1 label" >Titulo:</p>
					</div>
					<div class="col-sm-10">
						<p class="rounded border p-1">{{ incidente.titulo }}</p>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2">
						<p class="p-1 label">Fecha:</p>
					</div>
					<div class="col-sm-10">
						<p class="rounded border p-1"> {{ incidente.fecha_creacion }}</p>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2">
						<p class="p-1 label">Cliente:</p>
					</div>
					<div class="col-sm-10">
						<p class="rounded border p-1">{{ incidente.usuario.usuariosgrexco.empresa.nombre }}</p>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2">
						<p class="p-1 label">Aplicación:</p>
					</div>
					<div class="col-sm-10">
						<p class="rounded border p-1">{{ incidente.aplicacion.nombre }}</p>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2">
						<p class="p-1 label">Estado:</p>
					</div>
					<div class="col-sm-10">
						<p class="rounded border p-1">{{ incidente.estado.descripcion }}</p>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2">
						<p class="p-1 label">Descripción:</p>
					</div>
				</div>
				<div class="row">
					<div class="col border rounded p-2 ml-3">
						<p>{{ incidente.descripcion }}</p>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col">
				<div class="m-2">
					<hr>
					{% if adjuntos %}
						{% for adjunto in adjuntos %}
							<a class="btn btn-sm btn-outline-success" href="{{ adjunto.archivo.url }}">
								<i class="material-icons md-19 align-middle mr-1">attach_file</i>{{ adjunto.nombre_archivo }}
							</a>
						{% endfor %}
					{% else %}
						<p>No hay archivos adjuntos</p>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
{% else %}
	<div class="container-fluid">			
		<div class="row">
			<div class="col">
				<div class="row">
					<div class="col-sm-2">
						<p class="p-1 label" >Titulo:</p>
					</div>
					<div class="col-sm-10">
						<p class="rounded border p-1">{{ incidente.titulo }}</p>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2">
						<p class="p-1 label">Fecha:</p>
					</div>
					<div class="col-sm-10">
						<p class="rounded border p-1"> {{ incidente.fecha_creacion }}</p>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2">
						<p class="p-1 label">Cliente:</p>
					</div>
					<div class="col-sm-10">
						<p class="rounded border p-1">{{ incidente.usuario.usuariosgrexco.empresa.nombre }}</p>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2">
						<p class="p-1 label">Aplicación:</p>
					</div>
					<div class="col-sm-10">
						<p class="rounded border p-1">{{ incidente.aplicacion.nombre }}</p>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2">
						<p class="p-1 label">Estado:</p>
					</div>
					<div class="col-sm-10">
						<p class="rounded border p-1">{{ incidente.estado.descripcion }}</p>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2">
						<p class="p-1 label">Descripción:</p>
					</div>
				</div>
				<div class="row">
					<div class="col border rounded p-2 ml-3">
						<p>{{ incidente.descripcion }}</p>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col">
				<div class="m-2">
					<h6 class="mt-3 mb-0">Adjuntos</h6>
					<hr class="mt-1">
					{% if adjuntos %}
						{% for adjunto in adjuntos %}
							<a class="btn btn-sm btn-outline-success" href="{{ adjunto.archivo.url }}">
								<i class="material-icons md-19 align-middle mr-1">attach_file</i>{{ adjunto.nombre_archivo }}
							</a>
						{% endfor %}
					{% else %}
						<p>No hay archivos adjuntos</p>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
{% endif %}
    

<!-- Modal Asigna Incidentes -->
<div class="modal fade" id="modalSelUsuario" tabindex="-1" 
		 role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header bg-light">
        <h5 class="modal-title" id="exampleModalLabel">ASIGNAR CASO</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      	<div class="col">
      		<form action="" id="frmAsigInci" name="frmAsigInci">
      			<div class="form-group">
      				<label for="">Elija el usuario de <b>Soporte</b> al que desea asignarle este incidente:</label>
      				<select name="selUsuario" id="selUsuario" class="custom-select">
      					<option value=""></option>
      				</select>
      			</div>
      			<div class="form-group">
      				<label for="">Seleccione la prioridad de respuesta aplicable para el caso:</label>
      				<select name="selPrioResp" id="selPrioResp" class="custom-select">
      					<option value=""></option>
      				</select>
      			</div>
      		</form>
      	</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-dark btn-sm" data-dismiss="modal">Cancelar</button>
        <button id="btnEnviar" type="button" class="btn btn-primary btn-sm">Enviar</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
	<script src="{% static '/js/detalle_incidente.js' %}"></script>
{% endblock %}

grexco/soporte/templates/soporte/home.html
{% extends './base_contenido.html' %}

{% block title %}
	Soporte
{% endblock%}

{% block titulo_contenido %}
	<h4>Incidentes</h4>
{% endblock %}

{% block barra_herramientas %}
herramientas
{% endblock %}

{% block contenido %}
<div class="container-fluid">
	
	<table id="tblIncidentes" class="table table-striped">
		<thead>
			<tr>
				<td>Código</td>
				<td>Fecha</td>
				<td>Titulo</td>
				<td>Empresa</td>
				<td>Aplicación</td>
				<td>Estado</td>
			</tr>
		</thead>
		<tbody>
		</tbody>
	</table>
</div>
{% endblock %}

{% block js %}
	{% load static %}
	<script src="{% static '/js/soporte.js' %}"></script>
{% endblock %}