grexco/administracion/urls.py
"""aaaa."""
# from django.contrib.auth.views import logout
from django.urls import path

from . import views

app_name = 'administracion'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path(
        'aplicaciones/',
        views.AplicationsView.as_view(),
        name='aplicaciones'
    ),
    path(
        'aplicaciones/eliminar/',
        views.DeleteAplicationsView.as_view(),
        name='eliminar_aplicacion'
    ),
    path(
        'aplicaciones/listado/',
        views.ListadoAplicacionesView.as_view(),
        name='listado_aplicaciones'
    ),
    path(
        'aplicaciones/listado/excel/',
        views.ListExcelAplicationsView.as_view(),
        name='listado_aplicaciones_excel'
    ),
    path(
        'aplicaciones/nuevo/',
        views.CreateAplicationsView.as_view(),
        name='nueva_aplicacion'
    ),
    path('convenios/', views.ConveniosView.as_view(), name='convenios'),
    path(
        'convenios/agregar/',
        views.ConveniosAgregarView.as_view(),
        name='convenios_actualizar'
    ),
    path(
        'convenios/consulta/<str:nit>/',
        views.ConsultaConveniosView.as_view(),
        name='convenios_consulta'
    ),
    path(
        'convenios/consulta/individual/<str:nit>',
        views.ConveniosConsultaIndividualView.as_view()
    ),
    path(
        'convenios/retirar/',
        views.ConveniosRetirarView.as_view(),
        name='convenios_eliminar'
    ),
    path(
        'convenios/listado/empresas/',
        views.ListadoConveniosEmpresasView.as_view(),
        name='convenios_listado'
    ),
    path(
        'convenios/listado/no-convenios/<str:nit>/',
        views.ListadoNoConveniosEmpresasView.as_view(),
        name='no_convenios_listado'
    ),
    path(
        'convenios/nuevo/',
        views.CrearConveniosView.as_view(),
        name='convenios_nuevo'
    ),
    path('empresas/', views.CompaniesView.as_view(), name='empresas'),
    path(
        'empresas/actualizar/',
        views.ActualizaEmpresaView.as_view(),
        name='empresas_actualizar'
    ),
    path(
        'empresas/consulta/<str:nit>/',
        views.ConsultaEmpresaView.as_view(),
        name='consulta_empresas'
    ),
    path(
        'empresas/activar/',
        views.ActivaEmpresasView.as_view(),
        name='empresas_activar'
    ),
    path(
        'empresas/desactivar/',
        views.DesactivaEmpresasView.as_view(),
        name='empresas_desactivar'
    ),
    path(
        'empresas/listado/',
        views.ListadoBasicoEmpresasView.as_view(),
        name='lista_empresas'
    ),
    path(
        'empresas/listado/activas/',
        views.ListadoEmpresasActivas.as_view(),
        name='empresas_listado_activas'
    ),
    path(
        'empresas/nuevo/',
        views.CrearEmpresaView.as_view(),
        name='nueva_empresa'
    ),
    path(
        'horarios-soporte/',
        views.HorariosSoporteView.as_view(),
        name='horarios_soporte'
    ),
    path(
        'horarios-soporte/<int:nit>/',
        views.ConsultaHorariosSoporte.as_view(),
        name='horarios-soporte-consulta'
    ),
    path(
        'horarios-soporte/nuevo/',
        views.CrearHorariosSoporte.as_view(),
        name='nuevo_horario_soporte'
    ),
    path('plataformas/', views.PlataformasView.as_view(), name='plataformas'),
    path(
        'plataformas/eliminar/',
        views.EliminarPlataformasView.as_view(),
        name='eliminar_plataforma'
    ),
    path(
        'plataformas/listado/',
        views.ListadoBasicoPlataformasView.as_view(),
        name='listado_plataformas'
    ),
    path(
        'plataformas/nuevo/',
        views.CrearPlataformasView.as_view(),
        name='nueva_plataforma'
    ),
    path(
        'prioridades-respuesta/',
        views.PrioridadesRespuestaView.as_view(),
        name='prioridades_respuesta'
    ),
    path('reportes/', views.ReportsView.as_view(), name='reportes'),
    path(
        'reportes/nuevo/',
        views.CreateReportsView.as_view(),
        name='nuevo_reporte'
    ),
    path(
        'reportes/<int:id>/',
        views.DetailReportView.as_view(),
        name='detalle_reporte'
    ),
    path(
        'reportes/eliminar/',
        views.DeleteReportsView.as_view(),
        name='eliminar_reporte'
    ),
    path(
        'reportes/actualizar/',
        views.UpdateReportsView.as_view(),
        name='actualizar_reporte'
    ),
    path(
        'tiempos-respuesta/',
        views.TiemposRespuestaView.as_view(),
        name='tiempos_respuesta'
    ),
    path(
        'tiempos-respuesta/consulta/<int:nit>/',
        views.ConsultaTiemposRespuestaView.as_view(),
        name='tiempos_respuesta_consulta'
    ),
    path(
        'tiempos-respuesta/empresas/',
        views.TiemposRespuestaEmpresas.as_view(),
        name='tiempos_respuesta_empresas'
    ),
    path(
        'tiempos-respuesta/nuevo/',
        views.CrearTiemposRespuestaView.as_view(),
        name='tiempos_respuesta_nuevo'
    ),
    path(
        'tipos-incidentes/',
        views.TiposIncidentesView.as_view(),
        name='tipos_incidentes'
    ),
    path(
        'tipos-incidentes/listado/',
        views.TiposIncidentesListadoView.as_view(),
        name='tipos_incidentes_listado'
    ),
    path(
        'tipos-incidentes/nuevo/',
        views.TiposIncidentesNuevoView.as_view(),
        name='tipos_incidentes_nuevo'
    ),
    path(
        'tipos-incidentes/eliminar/',
        views.TiposIncidentesEliminar.as_view(),
        name='tipos_incidentes_eliminar'
    ),
    path(
        'usuarios/nuevo/usuario/',
        views.CrearUsuariosView.as_view(),
        name='nuevo_usuario'
    ),
    path(
        'usuarios/clientes/',
        views.ConsultClientsView.as_view(),
        name='clientes'
    ),
]

grexco/grexco/urls.py
from django.contrib import admin
from django.contrib.auth.views import logout
from django.urls import include, path

from usuarios.views import LoginView


urlpatterns = [
    path('', include('landing.urls')),
    path('a/', include('administracion.urls')),
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout, {'next_page': '/'}, name='logout'),
    path('usuarios/', include('usuarios.urls')),
    path('soporte/', include('soporte.urls')),
]

grexco/administracion/views.py
"""docstring."""
import json
from datetime import time

import pyexcel as pe
# from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.core import serializers
from django.core.exceptions import ObjectDoesNotExist
from django.db import connection
from django.db import IntegrityError
from django.db import transaction
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView
from django.views.generic import View

from administracion.models import Aplicaciones
from administracion.models import Convenios
from administracion.models import Empresas
from administracion.models import HorariosSoporte
from administracion.models import Plataformas
from administracion.models import PrioridadesRespuesta
from administracion.models import Reportes
from administracion.models import TiemposRespuesta
from administracion.models import TiposIncidentes
from administracion.models import UsuariosGrexco


def genera_id(modelo):
    """Recibe como parametro un Modelo de: administracion.models."""
    x = modelo.objects.last()
    if x is None:
        return 1
    else:
        return x.id + 1


def empresa_activa(nit):
    """
    Retorna True si la empresa esta activa, si no retorna False.

        :nit    :nit de la empresa a consultar.
    """
    empresa = get_object_or_404(Empresas, nit=nit)

    if empresa.activa:
        return True
    else:
        return False


def sql_a_diccionario(cursor):
    """
    Retorna las filas de la consulta como un diccionario.

    el cursor debe ser despues de:
        cursor.execute()
    """
    columnas = [columna[0] for columna in cursor.description]
    return [dict(zip(columnas, fila)) for fila in cursor.fetchall()]


# ............................................................................
# .                             Dahsboard                                    .
# ............................................................................
class DashboardView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    """docstring for DashboardView."""

    login_url = 'usuarios:login'
    template_name = 'administracion/dashboard.html'

    def test_func(self):
        """docstring."""
        return self.request.user.usuariosgrexco.tipo == 'A'


# ****************************************************************************
# *                            Plataformas                                   *
# ****************************************************************************

class PlataformasView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    """Vista para consultar plataformas."""

    login_url = 'administracion:admin_login'
    template_name = 'administracion/plataformas.html'

    def test_func(self):
        """Restringe el acceso solo a usuario administrador."""
        return self.request.user.usuariosgrexco.tipo == 'A'

    def get_context_data(self, *args, **kwargs):
        """Retorna un listado de las plataformas creadas."""
        plataforma = Plataformas.objects.all()

        return {'plataformas': plataforma}


class CrearPlataformasView(
        LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    """
    Vista para crear plataformas.

    * url: plataformas/nuevo/
    """

    login_url = 'usuarios:login'
    template_name = 'administracion/nueva_plataforma.html'

    def test_func(self):
        """Restringe el acceso solo a usuario administrador."""
        return self.request.user.usuariosgrexco.tipo == 'A'

    def post(self, request, *args, **kwargs):
        """Recibe los datos enviados para crear la nueva plataforma."""
        data = dict(request.POST)
        nombre = data['nombre'][0]
        version = data['version'][0]

        if not nombre or not version:
            return JsonResponse(
                {"error": "Los campos están vacíos"}, status=400)

        plataforma = Plataformas.objects.filter(
            nombre=nombre.upper(), version=version.upper())

        # Verifica si la plataforma ya existe
        if plataforma.exists():

            # Si existe retorna un error
            return JsonResponse({"error": "Los datos ya existen"}, status=400)
        else:

            # Si No existe la crea
            id = genera_id(Plataformas)
            plt = Plataformas(id=id, nombre=nombre.upper(), version=version)

            with transaction.atomic():
                try:
                    plt.save()
                except Exception as e:
                    mensaje = """
                            Ocurrió un error al grabar los datos: {}
                        """.format(e)
                    return JsonResponse({"error": mensaje}, status=400)

                mensaje = "Se guardó la plataforma: {}".format(plt)
                return JsonResponse({"ok": mensaje})


class EliminarPlataformasView(
        LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    """Vista para eliminar una plataforma."""

    login_url = 'usuarios:login'
    template_name = 'administracion/companies.html'

    def test_func(self):
        """Restringe el acceso solo a usuario administrador."""
        return self.request.user.usuariosgrexco.tipo == 'A'

    def post(self, request, *args, **kargs):
        """docstring."""
        data = dict(request.POST)
        # print(data)
        with transaction.atomic():
            for k, v in data.items():
                plataforma = get_object_or_404(Plataformas, id=int(data[k][0]))
                if plataforma:
                    from django.db.models.deletion import ProtectedError
                    try:
                        plataforma.delete()
                    except ProtectedError:
                        empresa = Empresas.objects.get(
                            plataforma__id=plataforma.id)
                        msj = """
                                No es posible eliminar: {}-{}.
                                Pertenece a la empresa: {}
                               """.format(
                            plataforma.nombre,
                            plataforma.version,
                            empresa.nombre
                        )
                        return JsonResponse({"error": msj}, status=400)

        mensaje = 'Se eliminó la plataforma: {}'.format(plataforma.nombre)
        return JsonResponse({"ok": mensaje}, status=200)


class ListadoBasicoPlataformasView(
        LoginRequiredMixin, UserPassesTestMixin, View):
    """
    Retorna un Json con los datos de las plataformas.

    Con el formato:
    """

    login_url = 'usuarios:login'

    def test_func(self):
        """Restringe el acceso solo a usuario administrador."""
        return self.request.user.usuariosgrexco.tipo == 'A'

    def get(self, request, *args, **kwargs):
        """docstring."""
        qry_plataformas = Plataformas.objects.values().all()
        plataformas = []
        for plataforma in qry_plataformas:
            plataformas.append(plataforma)

        return JsonResponse({'plataformas': plataformas}, status=200)


# ............................................................................
# .                                Aplicaciones                              .
# ............................................................................
class AplicationsView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    """Vista para consultar las aplicaciones."""

    login_url = 'usuarios:login'
    template_name = 'administracion/aplicaciones.html'

    def test_func(self):
        """Restringe el acceso solo a usuario administrador."""
        return self.request.user.usuariosgrexco.tipo == 'A'

    def get_context_data(self, *args, **kwargs):
        """docstring."""
        aplicaciones = Aplicaciones.objects.all()
        return {'aplicaciones': aplicaciones}

    def post(self, request, *args, **kwargs):
        """Retorna la información de: Versión y Convenios."""
        data = dict(request.POST)
        id = data['id'][0]
        app = Aplicaciones.objects.get(id=id)

        convenios = []
        qry_convenios = app.convenios.values(
            'empresa__nombre', 'empresa__nit').all()
        if len(qry_convenios) == 0:
            dic_convenios = {
                'empresa': 'Esta aplicación no es usada por ningún Cliente.'
            }
            convenios.append(dic_convenios)
        else:
            for convenio in qry_convenios:
                dic_convenios = {}
                dic_convenios['empresa'] = convenio['empresa__nombre']
                dic_convenios['nit'] = convenio['empresa__nit']
                convenios.append(dic_convenios)

        versiones = []
        qry_versiones = (
            app.versiones
               .values('version', 'fecha')
               .all()
               .order_by('-version')
        )
        if len(qry_versiones) == 0:
            dic_versiones = {
                'version': 'No tiene versiones',
                'fecha': 'No tiene versiones'
            }
            versiones.append(dic_versiones)
        else:
            for ver in qry_versiones:
                dic_versiones = {}
                dic_versiones['version'] = ver['version']
                dic_versiones['fecha'] = ver['fecha'].strftime(
                    format='%Y-%m-%d')
                versiones.append(dic_versiones)

        aplicacion = {
            'aplicacion': app.nombre,
            'versiones': versiones,
            'convenios': convenios
        }
        return JsonResponse({'aplicacion': aplicacion}, status=200)


class CreateAplicationsView(
        LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    """Vista para crear Aplicaciones."""

    login_url = 'usuarios:login'

    def test_func(self):
        """Restringe el acceso solo a usuario administrador."""

grexco/administracion/templates/administracion/alertas.html
<div class="row">
  <div class="col">
    <div style="width: 100%;">
                   
      <!-- Alerta ok -->
      <div class="alert alert-success alert-dismissible fade show p-1" id="alertaOk" style="display: none;">
        <div class="row">
          <div class="col-10" id="alertaOkMensaje">
          </div>
          <div class="col-2">
            <button type="button" class="close mr-3 p-0 btnCerrarAlerta">
              <i class="material-icons">close</i>
            </button>
          </div>
        </div>
      </div>

      <!-- Alerta error -->
      <div class="alert alert-danger alert-dismissible fade show p-1"
           id="alertaError"
           style="display: none;">
        <div class="row">
          <div class="col-10" id="alertaErrorMensaje">
          </div>
          <div class="col-2">
            <button type="button" class="close mr-3 p-0 btnCerrarAlerta">
              <i class="material-icons">close</i>
            </button>
          </div>  
        </div>
      </div>
    
    </div> 
  </div>
</div>

grexco/administracion/templates/administracion/base_dashboard.html
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block title %} {% endblock %}
	</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% load static %}

  <!-- CSS -->
  <link rel="stylesheet" type="text/css" href="{% static '/css/base_dashboard.css' %}">  

	<!-- Google Icons -->
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

	<!-- Font awesome -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

	{% block css %}

	{% endblock %}
	
</head>
<body style="font-size: .875rem; font-family: 'Roboto', sans-serif;"> 

<!-- Barra de navegación en mobiles -->
<nav class="navbar navbar-expand-lg bg-primary d-lg-none d-md-block d-sm-block">
	<div class="container-fluid">	
	    <!-- User -->
		  <div class="dropdown">
				<button class="btn bg-dark float-right pt-0 pb-0 pl-1 pr-1 dropdown-toggle btn-user" data-toggle="dropdown"><i class="material-icons md-36 person">person</i></button>
		    <div class="dropdown-menu">
				  <a class="dropdown-item" href="#"><b>Usuario:</b> {{request.user.username}}</a>
			  	<a class="dropdown-item" href="{% url 'logout'%}">Cerrar sesión</a>
				</div>
		  </div>
				
		  <!-- Toggler/collapsibe Button -->
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
		    <span><i class="material-icons">reorder</i></span>
		  </button>
				
			<!-- Navbar links -->
			<div class="collapse navbar-collapse" id="collapsibleNavbar">
			  <p>links</p>
				<button class="btn btn-block" type="button" data-toggle="collapse" data-target="#collapse-usuario">Usuario</button>
				<div class="collapse" id="collapse-usuario">
					usuario
				</div>
			</div>
	</div> 
</nav>
<!-- Fin barra de navegación en mobiles -->

<!-- Cuerpo -->
<div class="container-fluid">
	
	<!-- Top Nav -->
	<div class="row d-none d-lg-block">
		<nav class="nav bg-primary sticky-top p-1 clearfix" style="width: 100%; height: 50px;">
			<div class="col">
				<a href="/a/" class="navbar-brand pl-1" style="color: white; font-size: 22px;">
					GREXCO S.A.S
				</a>
			</div>
			<div class="col">				
				<div class="dropdown">
					<button class="btn btn-primary float-right p-1 m-0" data-toggle="dropdown">
						<i class="material-icons person">person</i>
					</button>
					<div class="dropdown-menu">
						<a href="#" class="dropdown-item">{{ request.user.username }}</a>
						<div class="dropdown-divider"></div>
						<a href="{% url 'logout' %}" class="dropdown-item">Cerrar sesión</a>
					</div>
				</div>
			</div>
		</nav>
	</div>
	<!-- Fin top nav -->
	
	<!-- Contenido -->
	<div class="row">

		<!-- sidebar -->
		<div class="col-md-2 d-none d-lg-block sidebar">
			<div class="sidebar-sticky p-0 pt-2">
				<!-- Usuarios -->
				<div class="m-1">
					<button class="btn btn-sm btn-toolbar btn-block menu-btn" 
							type="button" 
							data-toggle="collapse" 
							data-target="#collapseUsuarios"
							style="font-size: 15px; background-color: white !important">Usuarios
						<i class="material-icons ml-auto arrow">arrow_drop_down</i>
						<i class="material-icons ml-auto arrow" style="display: none;">arrow_drop_up</i>
  				</button>
  				<!-- Collapse -->
  				<div class="collapse" id="collapseUsuarios">
	  				<div class="card card-body p-1">
	  					<ul class="list-group listas-menu">  						
		  					<li class="list-group-item p-0 text-center">
			  					<a href="{% url 'administracion:nuevo_usuario' %}" class="btn btn-sm btn-block p-0">
										<i class="material-icons md-24">person_add</i>
		  						</a>
		  					</li>
	  					</ul>
	  					<hr class="m-1">
	  					<div>
	  						<ul class="list-group listas-menu">
	  							<li class="list-group-item p-0">
	  								<a href="{% url 'administracion:clientes' %}" class="btn btn-sm btn-block p-1 text-dark text-left" role="button">
	  								  Clientes
	  								</a>
	  							</li>
	  							<li class="list-group-item p-0">
	  								<a href="#"
	  									 class="btn btn-sm btn-block p-1 text-dark text-left"
	  									 role="button">
	  								  Soporte
	  								</a>
	  							</li>
	  							<li class="list-group-item p-0">
	  								<a href="#"
	  									 class="btn btn-sm btn-block p-1 text-dark text-left"
	  									 role="button">
	  									Tecnología
	  								</a>
	  							</li>
	  						</ul>	  						
	  					</div>
	  				</div>
					</div>
				</div>

				<!-- Clientes -->
				<div class="m-1">
					<button class="btn btn-sm btn-toolbar btn-block menu-btn" 
									type="button" 
									data-toggle="collapse" 
									data-target="#collapseClientes"
									style="font-size: 15px; background-color: white !important">
									Clientes
						<i class="material-icons ml-auto arrow">arrow_drop_down</i>
						<i class="material-icons ml-auto arrow" style="display: none;">arrow_drop_up</i>
					</button>
					<!-- Collapse -->
					<div class="collapse" id="collapseClientes">
						<div class="card card-body p-1">
							<div>
								<ul class="list-group listas-menu">
									<li class="list-group-item p-0">
										<a href="{% url 'administracion:plataformas' %}"
											 class="btn btn-sm btn-block p-1 text-dark text-left">Plataformas</a>
									</li>
									<li class="list-group-item p-0">
										<a href="{% url 'administracion:empresas' %}" 
											 class="btn btn-sm btn-block p-1 text-dark text-left">Empresas</a>
									</li>
									<li class="list-group-item p-0">
										<a href="{% url 'administracion:horarios_soporte' %}"
											 class="btn btn-sm btn-block p-1 text-dark text-left">Horarios de soporte</a>
									</li>
									<li class="list-group-item p-0">
										<a href="{% url 'administracion:tiempos_respuesta' %}"
											 class="btn btn-sm btn-block p-1 text-dark text-left">Tiempos de respuesta</a>
									</li>
   								<li class="list-group-item p-0">
										<a href="{% url 'administracion:convenios' %}"
											 class="btn btn-sm btn-block p-1 text-dark text-left">Convenios</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>

				<!-- Aplicaciones -->
				<div class="m-1">
					<button class="btn btn-sm btn-toolbar btn-block menu-btn"
									type="button"
									data-toggle="collapse" 
									data-target="#collapseAplicaciones"
									style="font-size: 15px; background-color: white !important">
							Aplicaciones
						<i class="material-icons ml-auto arrow">arrow_drop_down</i>
						<i class="material-icons ml-auto arrow" style="display: none;">arrow_drop_up</i>
					</button>
					<!-- Collapse -->
					<div class="collapse" id="collapseAplicaciones">
						<div class="card card-body p-1">
							<div>
								<ul class="list-group listas-menu">
									<li class="list-group-item p-0">
										<a href="{% url 'administracion:aplicaciones' %}"
											 class="btn btn-sm btn-block p-1 text-dark text-left"
											 role="button">
											Aplicaciones
										</a>
									</li>
									<li class="list-group-item p-0">
										<a href="{% url 'administracion:reportes' %}" 
											 class="btn btn-sm btn-block p-1 text-dark text-left" 
											 role="button">
											Reportes
										</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				
				<!-- Tipos Incidentes -->
				<div class="m-1">
					<button class="btn btn-sm btn-toolbar btn-block menu-btn" 
							type="button" 
							data-toggle="collapse" 
							data-target="#collapseTiposIncidentes"
							style="font-size: 15px; background-color: white !important">Tipos de Incidentes
						<i class="material-icons ml-auto arrow">arrow_drop_down</i>
						<i class="material-icons ml-auto arrow" style="display: none;">arrow_drop_up</i>
  				</button>
  				<!-- Collapse -->
  				<div class="collapse" id="collapseTiposIncidentes">
	  				<div class="card card-body p-1">
	  					<div>
	  						<ul class="list-group listas-menu">
	  							<li class="list-group-item p-0">
	  								<a href="{% url 'administracion:tipos_incidentes' %}"
	  									 class="btn btn-sm btn-block p-1 text-dark text-left"
	  									 role="button">
	  								  Consultar
	  								</a>
	  							</li>
	  						</ul>	  						
	  					</div>
	  				</div>
					</div>
				</div>

			</div>			
		</div>			
		<!-- Fin sidebar -->
		
		<main class="col-md-9">
			<div class="container-fluid">
				{% block content %}
				
				{% endblock %}
			</div>
		</main>
	
	</div>
	<!-- Fin contenido -->

</div>
<!-- Fin cuerpo -->

<!-- JQUERY -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="{% static '/js/base_dashboard.js' %}"></script>
<script src="{% static '/js/urls.js' %}"></script>

{% block js %}

{% endblock %}

</body>
</html>

grexco/administracion/templates/administracion/dashboard.html
{% extends './base_dashboard.html' %}


{% block content %}

	<div class="contenido">
		<p>Dashboard</p>
	</div>
	
{% endblock %}

grexco/administracion/templates/administracion/horarios_soporte_consulta.html
{% extends './base_dashboard.html' %}

{% load static %}

{% block css %}
<!-- Data tables -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.16/sl-1.2.5/datatables.min.css"/>

<style>
  .material-icons.md-18 {
    font-size: 18px;
  }
  
  .material-icons.md-19 {
    font-size: 19px;
  }

</style>
  
{% endblock %}

{% block js %}
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/jszip-2.5.0/dt-1.10.16/af-2.2.2/b-1.5.1/b-html5-1.5.1/b-print-1.5.1/r-2.2.1/sc-1.4.4/sl-1.2.5/datatables.min.js"></script>

<script src="{% static '/js/horarios_soporte_detalle.js' %}"></script>
{% endblock%}

{% block content %}
  {% csrf_token %}
  <div class="row">
    <div class="col-10 pt-2 pl-3">
      
      <!-- Breadcrumb -->
      <div class="row">
          <nav class="m-0 p-0">
            <ol class="breadcrumb m-0 pl-3" style="font-size: 20px; background-color: white;">
              <li class="breadcrumb-item">
                <a href="{% url 'administracion:horarios_soporte' %}">Horarios de Soporte</a>
              </li>
              <li class="breadcrumb-item">{{ horarios.empresa.nombre }}</li>
            </ol>
          </nav>
      </div>

      <!-- Almacena el nit del la empresa  -->
      <span id="idReporte" class="d-none">{{ horarios.empresa.nit }}</span>
            
      <!-- Info horarios de soporte -->
      <div class="row">
        <div class="pl-3 mt-3">
          <div class="col">
            <div class="card p-4 w-100">    
              <h5>Horarios:</h5>
              <table id="tblHorariosSoporte" class="table table-striped table-bordered table-responsive" style="width: 100%;">
                <thead>
                  <tr>
                    <td>Indice</td>
                    <td>Día</td>
                    <td>Hora Inicio</td>
                    <td>Hora Fin</td>
                  </tr>
                </thead>
                <tbody>
                  {% for row in horarios.horarios %}
                      <tr>
                        <td>{{ row.dia }}</td>
                        <td>{{ row.descripcion }}</td>
                        <td>{{ row.inicio }}</td>
                        <td>{{ row.fin }}</td>
                      </tr>
                  {% endfor %}
                </tbody>
              </table>  
            </div>
          </div>
        </div>
      </div>
      <!-- Fin info horarios de soporte -->

    </div>
  </div>
{% endblock %}