grexco/grexco/urls.py
from django.contrib import admin
from django.contrib.auth.views import logout
from django.urls import include, path

from usuarios.views import LoginView


urlpatterns = [
    path('', include('landing.urls')),
    path('a/', include('administracion.urls')),
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout, {'next_page': '/'}, name='logout'),
    path('usuarios/', include('usuarios.urls')),
    path('soporte/', include('soporte.urls')),
]

grexco/usuarios/urls.py
from django.urls import path

from . import views

app_name = 'usuarios'

urlpatterns = [
    path('', views.HomeUsuariosView.as_view(), name='home_usuarios'),
    path('incidentes/', views.IncidentesView.as_view(), name='incidentes'),
    path(
        'incidentes/codigo/',
        views.CodigoIncidentesJsonView.as_view(),
        name='codigo_incidentes'
    ),
    path(
        'incidentes/nuevo/',
        views.IncientesNuevoView.as_view(),
        name='incidentes_nuevo'
    ),
    path(
        'incidentes/consulta/json/<int:codigo>/',
        views.IncidentesConsultaIndividualJsonView.as_view(),
        name='incidentes_consulta'
    ),
    path(
        'incidentes/consulta/por-usuario/',
        views.IncidentesConsultaUsuarioJsonView.as_view(),
        name='incidentes_consulta_usuario'
    ),
]

grexco/usuarios/models.py
"""Se definen los models de la aplicación Usuarios."""
from django.db import models
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
import administracion.models as administracion

# Create your models here.

ubicacion_archivos = FileSystemStorage(
    location='/mnt/c/Users/arju/Desktop/Grexco/Proyectos/Web/grexco/usuarios/')


def my_awesome_upload_function(instance, filename):
    """Esta función retorn la ruta para guardar los archivos."""
    return 'incidentes/' + instance.incidente.codigo + '/' + 'adjuntos/' + filename


class EstadosIncidentes(models.Model):
    """
    Se definen los diferentes estados que tendran los incidentes.

        C = Creado (Cuando el cliente crea el incidente)
        S = Soporte (Cuando el caso es asignado a un integrante de soporte)
        T = Tecnología (Cuando soporte envia el caso a Tecnología)
        P = Pruebas (Cuando tecnologia lo devuelve a soporte)
        E = Entregado (Cuando soporte envia la respuesta al cliente)
        So = Solucionado (Cuando el cliente cierra el caso)
    """

    codigo = models.CharField(primary_key=True, max_length=3)
    descripcion = models.CharField(max_length=20)

    def __str__(self):
        """docstring."""
        return '{}:{}'.format(self.codigo, self.descripcion)


class Incidentes(models.Model):
    codigo = models.PositiveIntegerField(primary_key=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    titulo = models.CharField(max_length=80)
    descripcion = models.TextField()
    usuario = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='incidentes'
    )
    tipo_incidente = models.ForeignKey(
        administracion.TiposIncidentes,
        on_delete=models.PROTECT,
        related_name='incidentes',
        blank=True,
        null=True
    )
    reporte = models.ForeignKey(
        administracion.Reportes,
        on_delete=models.PROTECT,
        related_name='incidentes',
        blank=True,
        null=True
    )
    aplicacion = models.ForeignKey(
        administracion.Aplicaciones,
        on_delete=models.PROTECT,
        related_name='incidentes',
        blank=True,
        null=True
    )
    prioridad_respuesta = models.ForeignKey(
        administracion.PrioridadesRespuesta,
        on_delete=models.PROTECT,
        related_name='incidentes',
        blank=True,
        null=True
    )
    estado = models.ForeignKey(
        EstadosIncidentes,
        on_delete=models.PROTECT,
        related_name='incidentes'
    )
    fecha_respuesta = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        """docstring."""
        return 'codigo: {}'.format(self.codigo)


class Adjuntos(models.Model):
    incidente = models.ForeignKey(
        Incidentes, on_delete=models.CASCADE, related_name='adjuntos', default=0)
    nombre_archivo = models.CharField(max_length=250, blank=True, null=True)
    archivo = models.FileField(
        storage=ubicacion_archivos,
        upload_to=my_awesome_upload_function)

    def __str__(self):
        return 'incidente:{}, archivo:{}'.format(self.incidente, self.archivo)


class IncidentesReportes(models.Model):
    incidente = models.ForeignKey(
        Incidentes,
        related_name='incidentes_reportes',
        on_delete=models.PROTECT
    )
    reporte = models.ForeignKey(
        administracion.Reportes,
        related_name='incidentes_reportes',
        on_delete=models.PROTECT
    )

    def __str__(self):
        return "{}:{}".format(self.incidente, self.reporte)


class UsuariosSoporteIncidentes(models.Model):
    usuario = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='incidentes_soporte'
    )
    incidente = models.ForeignKey(
        Incidentes, on_delete=models.PROTECT, related_name='usuarios_soporte')

    def __str__(self):
        return '{}:{}'.format(self.usuario, self.incidente)


class UsuariosTecnologiaIncidentes(models.Model):
    usuario = models.ForeignKey(
        administracion.UsuariosGrexco,
        on_delete=models.CASCADE,
        related_name='incidentes_tecnologia'
    )
    incidente = models.ForeignKey(
        Incidentes,
        on_delete=models.PROTECT,
        related_name='usuarios_tecnologia'
    )

    def __str__(self):
        return '{usuario}:{incidente}'.format(self.usuario, self.incidente)


class MovimientosIncidentes(models.Model):
    incidente = models.ForeignKey(
        Incidentes, on_delete=models.PROTECT, related_name='movimientos')
    estado = models.ForeignKey(
        EstadosIncidentes,
        on_delete=models.PROTECT,
        related_name='movimientos'
    )
    responsable = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='movimentos_incidentes'
    )
    fecha = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}:{}:{}'.format(self.estado, self.incidente, self.fecha)


class RespuestasIncidentes(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    incidente = models.ForeignKey(
        Incidentes,
        on_delete=models.PROTECT,
        related_name='respuesta'
    )
    fecha = models.DateTimeField(auto_now_add=True)
    respuesta = models.TextField()

    def __str__(self):
        return '{}:{}'.format(self.id, self.respuesta)


class AdjuntosRespuestasIncidentes(models.Model):
    respuesta = models.ForeignKey(
        RespuestasIncidentes,
        on_delete=models.CASCADE,
        related_name='adjuntos'
    )
    archivo = models.FileField(
        storage=administracion.ubicacion_archivos,
        upload_to='incidentes/respuestas/{}'.format(respuesta)
    )

    def __str__(self):
        return '{}'.format(self.respuesta)

grexco/usuarios/views.py
"""Vistas para la aplicación Usuarios."""
from datetime import datetime
import json

from django.contrib.auth import authenticate, login  # , logout
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db import transaction
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, HttpResponse
from django.views.generic import TemplateView
from django.views.generic import View

from administracion.models import Aplicaciones
from administracion.views import empresa_activa

from usuarios.models import Adjuntos
from usuarios.models import EstadosIncidentes
from usuarios.models import Incidentes
from usuarios.models import MovimientosIncidentes


def codigos_incidentes():
    """Genera los codigo de los incidentes."""
    ultimo_incidente = Incidentes.objects.last()

    if ultimo_incidente is None:
        codigo = 1
    else:
        codigo = ultimo_incidente.codigo + 1

    return codigo


def convert_datetime_to_string(o):
    """docstring."""
    DATE_FORMAT = "%Y-%m-%d"
    TIME_FORMAT = "%H:%M:%S"

    if isinstance(o, datetime.date):
        return o.strftime(DATE_FORMAT)
    elif isinstance(o, datetime.time):
        return o.strftime(TIME_FORMAT)
    elif isinstance(o, datetime.datetime):
        return o.strftime("%s %s" % (DATE_FORMAT, TIME_FORMAT))


class LoginView(TemplateView):
    """docstring for LoginView."""

    template_name = 'usuarios/login.html'

    def post(self, request):
        """docstring."""
        data = json.loads(request.body.decode('utf-8'))
        usuario = data['usuario']
        password = data['contraseña']
        user = authenticate(request, username=usuario, password=password)

        if user is not None:
            login(request, user)

            # Dependiendo del tipo de usuario se envia a una URL
            # para redireccionar
            tipo = user.usuariosgrexco.tipo
            if tipo == 'A':
                return JsonResponse({'url': '/a/'}, status=200)
            elif tipo == 'C':
                return JsonResponse({'url': '/usuarios/'}, status=200)
            elif tipo == 'S':
                return JsonResponse({'url': '/soporte/'}, status=200)
            else:
                return JsonResponse({'url': '/'}, status=200)
        else:
            return HttpResponse(
                'Datos invalidos o usuario inactivo', status=400)


class HomeUsuariosView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    """Home para los clientes de Grexco."""

    login_url = 'usuarios:login'
    template_name = 'usuarios/home_usuarios.html'

    def test_func(self):
        """
        Retringe el acceso de usuarios.

        Solo permite el acceso a los usuarios:
            - Administrador
            - Cliente
        """
        tipo = self.request.user.usuariosgrexco.tipo
        return tipo == 'A' or tipo == 'C'


class IncidentesView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    """Template para consultar incidentes del cliente que este loggeado."""

    login_url = 'usuarios:login'
    template_name = 'usuarios/incidentes.html'

    def test_func(self):
        """
        Retringe el acceso de usuarios.

        Solo permite el acceso a los usuarios:
            - Administrador
            - Cliente
        """
        tipo = self.request.user.usuariosgrexco.tipo
        return tipo == 'A' or tipo == 'C'


class CodigoIncidentesJsonView(LoginRequiredMixin, UserPassesTestMixin, View):
    """Vista para generar los codigos de los incidentes."""

    login_url = 'usuarios:login'

    def test_func(self):
        """
        Retringe el acceso de usuarios.

        Solo permite el acceso a los usuarios:
            - Administrador
            - Cliente
        """
        tipo = self.request.user.usuariosgrexco.tipo
        return tipo == 'A' or tipo == 'C'

    def get(self, request):
        """Retorna un JSON con el código del incidente."""
        codigo = codigos_incidentes()
        return JsonResponse({'codigo': codigo}, status=200)


class IncientesNuevoView(
        LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    """Template para capturar un nuevo incidente."""

    login_url = 'usuarios:login'
    template_name = 'usuarios/incidentes_nuevo.html'

    def test_func(self):
        """
        Retringe el acceso de usuarios.

        Solo permite el acceso a los usuarios:
            - Administrador
            - Cliente
        """
        tipo = self.request.user.usuariosgrexco.tipo
        return tipo == 'A' or tipo == 'C'

    def post(self, request, *args, **kwargs):
        """Guardar los incidentes y sus archivos adjuntos."""
        data = dict(request.POST)
        codigo = data['codigo'][0]
        descripcion = data['descripcion'][0]
        aplicacion_id = data['selAplicacion'][0]
        titulo = data['titulo'][0]
        usuario = self.request.user
        nit = self.request.user.usuariosgrexco.empresa.nit
        aplicacion = get_object_or_404(Aplicaciones, id=aplicacion_id)
        estado = get_object_or_404(EstadosIncidentes, codigo='C')

        if empresa_activa(nit):
            pass
        else:
            return JsonResponse(
                {'error': 'La empresa esta inactiva'}, status=400)

        with transaction.atomic():
            # Guarda el incidente
            incidente = Incidentes(
                codigo=codigo,
                descripcion=descripcion,
                titulo=titulo,
                usuario=usuario,
                aplicacion=aplicacion,
                estado=estado
            )
            try:
                incidente.save()
            except Exception as e:
                return JsonResponse(
                    {'error': 'Ocurrio un error: {}'.format(e)}, status=400)

            # Guarda los archivos adjuntos
            if request.FILES:
                archivos = request.FILES.getlist('inpAdjuntos')
                for archivo in archivos:
                    adjunto = Adjuntos(
                        incidente=incidente,
                        archivo=archivo,
                        nombre_archivo=archivo
                    )
                    try:
                        adjunto.save()
                    except Exception as e:
                        return JsonResponse(
                            {'error': 'Ocurrio un error: {}'.format(e)},
                            status=400
                        )
                        break
            else:
                print('No hay adjuntos')

            # Guarda el movimiento
            movimiento = MovimientosIncidentes(
                incidente=incidente, estado=estado, responsable=usuario)
            try:
                movimiento.save()
            except Exception as e:
                return JsonResponse(
                    {'error': 'Ocurrio un error: {}'.format(e)}, status=400)

            return JsonResponse({'ok': 'Se creó el incidente correctamente'})


class IncidentesConsultaIndividualJsonView(
        LoginRequiredMixin, UserPassesTestMixin, View):
    """Retorna un JSON con la info del Incidente consultado."""

    login_url = 'usuarios:login'

    def test_func(self):
        """
        Retringe el acceso de usuarios.

        Solo permite el acceso a los usuarios:
            - Administrador
            - Cliente
        """
        tipo = self.request.user.usuariosgrexco.tipo
        return tipo == 'A' or tipo == 'C' or tipo == 'S'

    def get(self, request, **kwargs):
        """Retorna un Json con la información del incidente consultado."""
        codigo = kwargs['codigo']
        qry_incidente = (
            Incidentes.objects
                      .filter(codigo=codigo)
                      .values(
                          'codigo',
                          'titulo',
                          'descripcion',
                          'aplicacion__nombre',
                          'fecha_creacion',
                          'usuario__empresa__nombre',
                          'fecha_respuesta',
                          'prioridad_respuesta__descripcion',
                          'tipo_incidente__descripcion',
                      )
        )
        qry_adjuntos = Adjuntos.objects.filter(
            incidente__codigo=codigo).values('archivo')

        if qry_incidente:
            incidente = qry_incidente[0]
            listado_adjuntos = []
            for archivo in qry_adjuntos:
                for k, v in archivo.items():
                    listado_adjuntos.append(v)

            return JsonResponse(
                {'incidente': incidente, 'adjuntos': listado_adjuntos},
                status=200
            )
        else:
            return JsonResponse(
                {'incidente': 'No hay incidentes con este código'},
                status=400
            )


class IncidentesConsultaView(
        LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    """
    Template para consultar un incidente.

    url =
    """

    login_url = 'usuarios:login'
    template_name = 'usuarios/incidentes_consulta.html'

    def test_func(self):
        """
        Retringe el acceso de usuarios.

        Solo permite el acceso a los usuarios:
            - Administrador
            - Cliente
        """
        tipo = self.request.user.usuariosgrexco.tipo
        return tipo == 'A' or tipo == 'C'


class IncidentesConsultaUsuarioJsonView(
        LoginRequiredMixin, UserPassesTestMixin, View):
    """
    Retorna un listado de incidentes creados por el usuario loggeado.

    url = 'incidentes/consulta/por-usuario/'
    """

    login_url = 'usuarios:login'

    def test_func(self):
        """
        Retringe el acceso de usuarios.

        Solo permite el acceso a los usuarios:
            - Administrador
            - Cliente
        """
        tipo = self.request.user.usuariosgrexco.tipo
        return tipo == 'A' or tipo == 'C'

    def get(self, request):

grexco/usuarios/templates/usuarios/base_home.html
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block title %} {% endblock %}
	</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% load static %}

	<!-- Jquery -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	<!-- CSS DataTables -->
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/b-1.5.2/b-print-1.5.2/sc-1.5.0/sl-1.2.6/datatables.min.css"/>

	<!-- JS DataTables --> 
	<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/b-1.5.2/b-print-1.5.2/sc-1.5.0/sl-1.2.6/datatables.min.js"></script>

	<!-- Bootstrap -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="{% static '/bootstrap-4.1.1/dist/js/bootstrap.min.js' %}"></script>
	
	<!-- CSS Bootstrap -->
	<link rel="stylesheet" href="{% static '/bootstrap-4.1.1/dist/css/bootstrap.min.css' %}">
		
	<!-- Google Icons -->
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

	<!-- Font awesome -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

	<!-- CSS -->
	<link rel="stylesheet" href="{% static '/css/base.css' %}">

	{% block css %}

	{% endblock %}
	
</head>
<body style="font-size: .875rem; font-family: 'Roboto', sans-serif;">
	
	<!-- Top nav -->
	<nav class="nav bg-primary sticky-top clearfix shadow" style="width: 100%; height: 40px;">
		<div class="col">
			<a href="#" class="navbar-brand" style="color: white; font-size: 20px;">GREXCO</a>
		</div>
		<div class="col">				
			<div class="dropdown">
				<button class="btn btn-sm btn-primary float-right p-0" data-toggle="dropdown">
					<i class="material-icons person md-30">person</i>
				</button>
				<div class="dropdown-menu p-0">
					<a href="#" class="dropdown-item p-1 text-center">{{ request.user.username }}</a>
					<i id="nitEmpresa" class="d-none">{{ request.user.usuariosgrexco.empresa.nit }}</i>
					<div class="dropdown-divider m-1"></div>
					<a href="{% url 'logout' %}"
						 class="dropdown-item p-1 text-center"
						 style="font-size: 15px;">
						<i class="material-icons align-middle">exit_to_app</i> 
						Cerrar sesión
					</a>
				</div>
			</div>
		</div>
	</nav>
	<!-- Fin top nav -->

  <div class="container-fluid">
    <div class="row">
			
			<!-- Sidebar -->
      <nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="sidebar-sticky mb-3">
        	
        	<!-- Acordión -->
        	<div class="accordion m-1 mt-2">
        		<button class="btn btn-sm btn-block btn-light text-left text-primary"
        						type="button" 
        						data-toggle="collapse" 
        						data-target="#collapseIncidentes" 
        						style="font-size: 15px;">
        			Incidentes
        		</button>
        		<div id="collapseIncidentes" class="collapse pl-4">
							<nav class="nav flex-column">
								<a href="{% url 'usuarios:incidentes_nuevo' %}" class="nav-link p-1">Nuevo</a>
								<a href="{% url 'usuarios:incidentes' %}" class="nav-link p-1">Consultar</a>
							</nav>
        		</div>
        	</div>
        	<a class="btn btn-sm btn-block btn-light text-left text-primary"
        			href="" 
        			style="font-size: 15px;">
        		Actualizaciones <span class="badge badge-danger">1</span>
        	</a>
        	<!-- Fin acordión -->

        </div>
      </nav>
      <!-- Fin sidebar -->

			<!-- Contenido -->
      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
      	{% block contenedor %}
      	{% endblock %}
      </main>
      <!-- Fin contenido -->
    </div>
  </div>
	
	<script src="{% static '/js/urls.js' %}"></script>

	{% block js %}

	{% endblock %}

</body>
</html>

grexco/usuarios/templates/usuarios/home_usuarios.html
{% extends './base_contenido.html' %}

{% block title %}
	Incidentes
{% endblock %}

{% block titulo_contenido %}
	<h3>Incidentes</h3>
{% endblock %}

{% block barra_herramientas %}

{% endblock %}

{% block contenido %}
	<p>Contenido</p>
{% endblock %}

grexco/usuarios/templates/usuarios/incidentes.html
{% extends './base_contenido.html' %}

{% block title %}
	Incidentes
{% endblock %}

{% block titulo_contenido %}
	<h3>Incidentes</h3>
{% endblock %}

{% block barra_herramientas %}
	<a href="{% url 'usuarios:incidentes_nuevo' %}" class="btn btn-sm btn-primary text-white">
		<i class="material-icons md-30 align-middle">library_add</i> Nuevo
	</a>
	<button class="btn btn-sm btn-info ml-1" id="btnConsultar"><i class="material-icons md-22 align-middle">search</i>Consultar</button>
{% endblock %}

{% block contenido %}
	{% load static %}
	<div class="container-fluid">
		<div class="row">
			<div class="col">
				<table class="table table-striped table-sm" id="tblIncidentes">
					<thead class="thead-light">
						<tr class="text-center">
							<td>Código</td>
							<td>Titulo</td>
							<td>Aplicación</td>
							<td>Estado</td>
							<td>Fecha</td>
						</tr>
					</thead>
				</table>
			</div>
		</div>
	</div>
	
	{% block css %}

	{% endblock %}

	{% block js %}
		<script src="{% static '/js/incidentes.js' %}"></script>
	{% endblock %}

{% endblock %}

grexco/usuarios/templates/usuarios/incidentes_nuevo.html
{% extends './base_contenido.html' %}

{% load static %}


{% block title %}
	Incidentes | Nuevo
{% endblock %}


{% block js %}
	<script src="{% static '/js/urls.js' %}"></script>
	<script src="{% static '/js/nuevo_incidente.js' %}"></script>
{% endblock %}

{% block titulo_contenido %}
	<h3>Nuevo Incidente</h3>
{% endblock %}

{% block barra_herramientas %}
	<i class="fa fa-circle-o-notch fa-spin" style="font-size:24px; color: DodgerBlue; display: none;"></i>
	<button id="btnGuardar" class="btn btn-sm btn-primary">Guardar</button>
{% endblock %}

{% block contenido %}
	{% csrf_token %}
	<div class="container-fluid">
		<div class="row shadow-sm p-1">
			<div class="col">
				{% include './alertas.html' %}
				<form style="font-size: 15px;" id="formIncidente" name="formIncidente">
					<div class="form-group row">
						<label for="" class="col-sm-1 col-form-label">Código:</label>
						<div class="col-sm-4">
							<input type="text" class="form-control" id="inpCodigo" value="" name="inpCodigo" disabled>
							<input type="text" class="form-control d-none" id="codigo" value="" name="codigo">
						</div>
					</div>
					<div class="form-group row">
						<label for="" class="col-sm-1 col-form-label">Aplicación:</label>
						<div class="col-sm-4">
							<select name="selAplicacion" id="selAplicacion" class="form-control">
								<option value=""></option>
							</select>
						</div>
					</div>
					<div class="form-group row">
						<label for="" class="col-sm-1 col-form-label">Titulo:</label>
						<div class="col-sm-7">
							<input type="text" class="form-control" id="inpTitulo" name="titulo" maxlength="80">
						</div>
					</div>
					<div class="form-group">
						<label for="" class="form-control-label-label">Descripción:</label><br>
						<textarea id="descripcion"
											name="descripcion"
											cols="100"
											rows="10"
											class="rounded"
											placeholder="Por favor, recuerde digitar la ruta en la que se presenta el error."></textarea>
					</div>
					<div class="row">
						<div class="col">
							<label class="btn btn-sm btn-outline-dark p-1 pl-4 pr-4">
							  <i class="material-icons md-19 align-middle mr-1">attach_file</i>Adjuntar Archivos
							  <input type="file" style="display: none;" id="inpAdjuntos" name="inpAdjuntos" multiple>
							</label>
						</div>
          </div>
				</form>
				<div class="row mt-0" id="listadoAdjuntos">
				</div>
			</div>
		</div>
	</div>
{% endblock %}

grexco/usuarios/templates/usuarios/index_usuarios.html
{% extends './base_contenido.html' %}

{% block title %}
	Incidentes
{% endblock %}

{% block titulo_contenido %}
	<h3>Incidentes</h3>
{% endblock %}

{% block barra_herramientas %}

{% endblock %}

{% block contenido %}

{% endblock %}

grexco/usuarios/templates/usuarios/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/gif/png" href="{% static '/img/icono.png' %}">
  
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	
	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

	<!-- Font awesome -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

	<!-- JQUERY -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	<!-- Bootstrap JS -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

  <script src="{% static '/js/login.js' %}"></script>
	
	<style>
		body
		{
			background-color: #E6E6E6; 
			font-family: 'Roboto';
		}

		main {
			height: 70%;
		}

		.footer {
		  position: absolute;
		  bottom: 0;
		  width: 100%;
		  height: 7%; /* Set the fixed height of the footer here */
		  line-height: 60px; /* Vertically center the text there */
		  background-color: #f5f5f5;
		}

	</style>
</head>
<body>
	<main>
		<div class="container-fluid">
			<div class="row">
				<div class="col">
					<div class="d-flex justify-content-center align-items-center">
						<div class="p-3 mt-5 bg-white rounded" style="width: 450px;">
			   			<div class="text-center mt-4">
			   				<img src="{% static '/img/logo.jpg' %}" class="w-100">
			   			</div>
			   			<div class="text-center text-secondary mt-4">
			   				<h5>Iniciar Sesión:</h5>
			   			</div>
			   			<div class="p-3">
								<form action="." method="POST">
									{% csrf_token %}
									<div class="form-group">
								    <input type="text" class="form-control" placeholder="Usuario" id="usuario">
									</div>
		  						<div class="form-group">
							    	<input type="password" class="form-control" placeholder="Contraseña" id="contraseña">
		  						</div>
		  						<input type="submit" class="btn btn-primary btn-block" id="btnIngresar" value="Ingresar">
								</form>
			   			</div>
			   			<div class="p-3">
			   				{% include './alertas.html' %}
			   			</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</main>

	<footer class="footer">
		<div class="container-fluid">
			<p style="font-size: 13px;">Todos los derechos reservados - GREXCO S.A.S - Calle 60 A # 5 54 Oficina 304, Bogotá - Colombia - +57 031 2351180 </p>
		</div>
	</footer>

</body>
</html>