grexco/administracion/urls.py
"""aaaa."""
# from django.contrib.auth.views import logout
from django.urls import path

from . import views

app_name = 'administracion'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path(
        'aplicaciones/',
        views.AplicationsView.as_view(),
        name='aplicaciones'
    ),
    path(
        'aplicaciones/eliminar/',
        views.DeleteAplicationsView.as_view(),
        name='eliminar_aplicacion'
    ),
    path(
        'aplicaciones/listado/',
        views.ListadoAplicacionesView.as_view(),
        name='listado_aplicaciones'
    ),
    path(
        'aplicaciones/listado/excel/',
        views.ListExcelAplicationsView.as_view(),
        name='listado_aplicaciones_excel'
    ),
    path(
        'aplicaciones/nuevo/',
        views.CreateAplicationsView.as_view(),
        name='nueva_aplicacion'
    ),
    path('convenios/', views.ConveniosView.as_view(), name='convenios'),
    path(
        'convenios/agregar/',
        views.ConveniosAgregarView.as_view(),
        name='convenios_actualizar'
    ),
    path(
        'convenios/consulta/<str:nit>/',
        views.ConsultaConveniosView.as_view(),
        name='convenios_consulta'
    ),
    path(
        'convenios/consulta/individual/<str:nit>',
        views.ConveniosConsultaIndividualView.as_view()
    ),
    path(
        'convenios/retirar/',
        views.ConveniosRetirarView.as_view(),
        name='convenios_eliminar'
    ),
    path(
        'convenios/listado/empresas/',
        views.ListadoConveniosEmpresasView.as_view(),
        name='convenios_listado'
    ),
    path(
        'convenios/listado/no-convenios/<str:nit>/',
        views.ListadoNoConveniosEmpresasView.as_view(),
        name='no_convenios_listado'
    ),
    path(
        'convenios/nuevo/',
        views.CrearConveniosView.as_view(),
        name='convenios_nuevo'
    ),
    path('empresas/', views.CompaniesView.as_view(), name='empresas'),
    path(
        'empresas/actualizar/',
        views.ActualizaEmpresaView.as_view(),
        name='empresas_actualizar'
    ),
    path(
        'empresas/consulta/<str:nit>/',
        views.ConsultaEmpresaView.as_view(),
        name='consulta_empresas'
    ),
    path(
        'empresas/activar/',
        views.ActivaEmpresasView.as_view(),
        name='empresas_activar'
    ),
    path(
        'empresas/desactivar/',
        views.DesactivaEmpresasView.as_view(),
        name='empresas_desactivar'
    ),
    path(
        'empresas/listado/',
        views.ListadoBasicoEmpresasView.as_view(),
        name='lista_empresas'
    ),
    path(
        'empresas/listado/activas/',
        views.ListadoEmpresasActivas.as_view(),
        name='empresas_listado_activas'
    ),
    path(
        'empresas/nuevo/',
        views.CrearEmpresaView.as_view(),
        name='nueva_empresa'
    ),
    path(
        'horarios-soporte/',
        views.HorariosSoporteView.as_view(),
        name='horarios_soporte'
    ),
    path(
        'horarios-soporte/<int:nit>/',
        views.ConsultaHorariosSoporte.as_view(),
        name='horarios-soporte-consulta'
    ),
    path(
        'horarios-soporte/nuevo/',
        views.CrearHorariosSoporte.as_view(),
        name='nuevo_horario_soporte'
    ),
    path('plataformas/', views.PlataformasView.as_view(), name='plataformas'),
    path(
        'plataformas/eliminar/',
        views.EliminarPlataformasView.as_view(),
        name='eliminar_plataforma'
    ),
    path(
        'plataformas/listado/',
        views.ListadoBasicoPlataformasView.as_view(),
        name='listado_plataformas'
    ),
    path(
        'plataformas/nuevo/',
        views.CrearPlataformasView.as_view(),
        name='nueva_plataforma'
    ),
    path(
        'prioridades-respuesta/',
        views.PrioridadesRespuestaView.as_view(),
        name='prioridades_respuesta'
    ),
    path('reportes/', views.ReportsView.as_view(), name='reportes'),
    path(
        'reportes/nuevo/',
        views.CreateReportsView.as_view(),
        name='nuevo_reporte'
    ),
    path(
        'reportes/<int:id>/',
        views.DetailReportView.as_view(),
        name='detalle_reporte'
    ),
    path(
        'reportes/eliminar/',
        views.DeleteReportsView.as_view(),
        name='eliminar_reporte'
    ),
    path(
        'reportes/actualizar/',
        views.UpdateReportsView.as_view(),
        name='actualizar_reporte'
    ),
    path(
        'tiempos-respuesta/',
        views.TiemposRespuestaView.as_view(),
        name='tiempos_respuesta'
    ),
    path(
        'tiempos-respuesta/consulta/<int:nit>/',
        views.ConsultaTiemposRespuestaView.as_view(),
        name='tiempos_respuesta_consulta'
    ),
    path(
        'tiempos-respuesta/empresas/',
        views.TiemposRespuestaEmpresas.as_view(),
        name='tiempos_respuesta_empresas'
    ),
    path(
        'tiempos-respuesta/nuevo/',
        views.CrearTiemposRespuestaView.as_view(),
        name='tiempos_respuesta_nuevo'
    ),
    path(
        'tipos-incidentes/',
        views.TiposIncidentesView.as_view(),
        name='tipos_incidentes'
    ),
    path(
        'tipos-incidentes/listado/',
        views.TiposIncidentesListadoView.as_view(),
        name='tipos_incidentes_listado'
    ),
    path(
        'tipos-incidentes/nuevo/',
        views.TiposIncidentesNuevoView.as_view(),
        name='tipos_incidentes_nuevo'
    ),
    path(
        'tipos-incidentes/eliminar/',
        views.TiposIncidentesEliminar.as_view(),
        name='tipos_incidentes_eliminar'
    ),
    path(
        'usuarios/nuevo/usuario/',
        views.CrearUsuariosView.as_view(),
        name='nuevo_usuario'
    ),
    path(
        'usuarios/clientes/',
        views.ConsultClientsView.as_view(),
        name='clientes'
    ),
]

grexco/grexco/urls.py
from django.contrib import admin
from django.contrib.auth.views import logout
from django.urls import include, path

from usuarios.views import LoginView


urlpatterns = [
    path('', include('landing.urls')),
    path('a/', include('administracion.urls')),
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout, {'next_page': '/'}, name='logout'),
    path('usuarios/', include('usuarios.urls')),
    path('soporte/', include('soporte.urls')),
]

grexco/usuarios/urls.py
from django.urls import path

from . import views

app_name = 'usuarios'

urlpatterns = [
    path('', views.HomeUsuariosView.as_view(), name='home_usuarios'),
    path('incidentes/', views.IncidentesView.as_view(), name='incidentes'),
    path(
        'incidentes/codigo/',
        views.CodigoIncidentesJsonView.as_view(),
        name='codigo_incidentes'
    ),
    path(
        'incidentes/nuevo/',
        views.IncientesNuevoView.as_view(),
        name='incidentes_nuevo'
    ),
    path(
        'incidentes/consulta/json/<int:codigo>/',
        views.IncidentesConsultaIndividualJsonView.as_view(),
        name='incidentes_consulta'
    ),
    path(
        'incidentes/consulta/por-usuario/',
        views.IncidentesConsultaUsuarioJsonView.as_view(),
        name='incidentes_consulta_usuario'
    ),
]

grexco/administracion/views.py
"""docstring."""
import json
from datetime import time

import pyexcel as pe
# from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.core import serializers
from django.core.exceptions import ObjectDoesNotExist
from django.db import connection
from django.db import IntegrityError
from django.db import transaction
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView
from django.views.generic import View

from administracion.models import Aplicaciones
from administracion.models import Convenios
from administracion.models import Empresas
from administracion.models import HorariosSoporte
from administracion.models import Plataformas
from administracion.models import PrioridadesRespuesta
from administracion.models import Reportes
from administracion.models import TiemposRespuesta
from administracion.models import TiposIncidentes
from administracion.models import UsuariosGrexco


def genera_id(modelo):
    """Recibe como parametro un Modelo de: administracion.models."""
    x = modelo.objects.last()
    if x is None:
        return 1
    else:
        return x.id + 1


def empresa_activa(nit):
    """
    Retorna True si la empresa esta activa, si no retorna False.

        :nit    :nit de la empresa a consultar.
    """
    empresa = get_object_or_404(Empresas, nit=nit)

    if empresa.activa:
        return True
    else:
        return False


def sql_a_diccionario(cursor):
    """
    Retorna las filas de la consulta como un diccionario.

    el cursor debe ser despues de:
        cursor.execute()
    """
    columnas = [columna[0] for columna in cursor.description]
    return [dict(zip(columnas, fila)) for fila in cursor.fetchall()]


# ............................................................................
# .                             Dahsboard                                    .
# ............................................................................
class DashboardView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    """docstring for DashboardView."""

    login_url = 'usuarios:login'
    template_name = 'administracion/dashboard.html'

    def test_func(self):
        """docstring."""
        return self.request.user.usuariosgrexco.tipo == 'A'


# ****************************************************************************
# *                            Plataformas                                   *
# ****************************************************************************

class PlataformasView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    """Vista para consultar plataformas."""

    login_url = 'administracion:admin_login'
    template_name = 'administracion/plataformas.html'

    def test_func(self):
        """Restringe el acceso solo a usuario administrador."""
        return self.request.user.usuariosgrexco.tipo == 'A'

    def get_context_data(self, *args, **kwargs):
        """Retorna un listado de las plataformas creadas."""
        plataforma = Plataformas.objects.all()

        return {'plataformas': plataforma}


class CrearPlataformasView(
        LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    """
    Vista para crear plataformas.

    * url: plataformas/nuevo/
    """

    login_url = 'usuarios:login'
    template_name = 'administracion/nueva_plataforma.html'

    def test_func(self):
        """Restringe el acceso solo a usuario administrador."""
        return self.request.user.usuariosgrexco.tipo == 'A'

    def post(self, request, *args, **kwargs):
        """Recibe los datos enviados para crear la nueva plataforma."""
        data = dict(request.POST)
        nombre = data['nombre'][0]
        version = data['version'][0]

        if not nombre or not version:
            return JsonResponse(
                {"error": "Los campos están vacíos"}, status=400)

        plataforma = Plataformas.objects.filter(
            nombre=nombre.upper(), version=version.upper())

        # Verifica si la plataforma ya existe
        if plataforma.exists():

            # Si existe retorna un error
            return JsonResponse({"error": "Los datos ya existen"}, status=400)
        else:

            # Si No existe la crea
            id = genera_id(Plataformas)
            plt = Plataformas(id=id, nombre=nombre.upper(), version=version)

            with transaction.atomic():
                try:
                    plt.save()
                except Exception as e:
                    mensaje = """
                            Ocurrió un error al grabar los datos: {}
                        """.format(e)
                    return JsonResponse({"error": mensaje}, status=400)

                mensaje = "Se guardó la plataforma: {}".format(plt)
                return JsonResponse({"ok": mensaje})


class EliminarPlataformasView(
        LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    """Vista para eliminar una plataforma."""

    login_url = 'usuarios:login'
    template_name = 'administracion/companies.html'

    def test_func(self):
        """Restringe el acceso solo a usuario administrador."""
        return self.request.user.usuariosgrexco.tipo == 'A'

    def post(self, request, *args, **kargs):
        """docstring."""
        data = dict(request.POST)
        # print(data)
        with transaction.atomic():
            for k, v in data.items():
                plataforma = get_object_or_404(Plataformas, id=int(data[k][0]))
                if plataforma:
                    from django.db.models.deletion import ProtectedError
                    try:
                        plataforma.delete()
                    except ProtectedError:
                        empresa = Empresas.objects.get(
                            plataforma__id=plataforma.id)
                        msj = """
                                No es posible eliminar: {}-{}.
                                Pertenece a la empresa: {}
                               """.format(
                            plataforma.nombre,
                            plataforma.version,
                            empresa.nombre
                        )
                        return JsonResponse({"error": msj}, status=400)

        mensaje = 'Se eliminó la plataforma: {}'.format(plataforma.nombre)
        return JsonResponse({"ok": mensaje}, status=200)


class ListadoBasicoPlataformasView(
        LoginRequiredMixin, UserPassesTestMixin, View):
    """
    Retorna un Json con los datos de las plataformas.

    Con el formato:
    """

    login_url = 'usuarios:login'

    def test_func(self):
        """Restringe el acceso solo a usuario administrador."""
        return self.request.user.usuariosgrexco.tipo == 'A'

    def get(self, request, *args, **kwargs):
        """docstring."""
        qry_plataformas = Plataformas.objects.values().all()
        plataformas = []
        for plataforma in qry_plataformas:
            plataformas.append(plataforma)

        return JsonResponse({'plataformas': plataformas}, status=200)


# ............................................................................
# .                                Aplicaciones                              .
# ............................................................................
class AplicationsView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    """Vista para consultar las aplicaciones."""

    login_url = 'usuarios:login'
    template_name = 'administracion/aplicaciones.html'

    def test_func(self):
        """Restringe el acceso solo a usuario administrador."""
        return self.request.user.usuariosgrexco.tipo == 'A'

    def get_context_data(self, *args, **kwargs):
        """docstring."""
        aplicaciones = Aplicaciones.objects.all()
        return {'aplicaciones': aplicaciones}

    def post(self, request, *args, **kwargs):
        """Retorna la información de: Versión y Convenios."""
        data = dict(request.POST)
        id = data['id'][0]
        app = Aplicaciones.objects.get(id=id)

        convenios = []
        qry_convenios = app.convenios.values(
            'empresa__nombre', 'empresa__nit').all()
        if len(qry_convenios) == 0:
            dic_convenios = {
                'empresa': 'Esta aplicación no es usada por ningún Cliente.'
            }
            convenios.append(dic_convenios)
        else:
            for convenio in qry_convenios:
                dic_convenios = {}
                dic_convenios['empresa'] = convenio['empresa__nombre']
                dic_convenios['nit'] = convenio['empresa__nit']
                convenios.append(dic_convenios)

        versiones = []
        qry_versiones = (
            app.versiones
               .values('version', 'fecha')
               .all()
               .order_by('-version')
        )
        if len(qry_versiones) == 0:
            dic_versiones = {
                'version': 'No tiene versiones',
                'fecha': 'No tiene versiones'
            }
            versiones.append(dic_versiones)
        else:
            for ver in qry_versiones:
                dic_versiones = {}
                dic_versiones['version'] = ver['version']
                dic_versiones['fecha'] = ver['fecha'].strftime(
                    format='%Y-%m-%d')
                versiones.append(dic_versiones)

        aplicacion = {
            'aplicacion': app.nombre,
            'versiones': versiones,
            'convenios': convenios
        }
        return JsonResponse({'aplicacion': aplicacion}, status=200)


class CreateAplicationsView(
        LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    """Vista para crear Aplicaciones."""

    login_url = 'usuarios:login'

    def test_func(self):
        """Restringe el acceso solo a usuario administrador."""

grexco/grexco/templates/administracion/base_dashboard.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Administración</title>
  {% load static %}
  <!-- CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'administracion/css/base_dashboard.css' %}">  

	<!-- Jquery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  {% block js-css %}

  {% endblock %}
    
  <!-- Google Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!-- Google fonts  -->
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>

</head>
<body>
<!-- TOP BAR -->
  <nav>
  	<a href="{% url 'administracion:dashboard'%}">
			<img src="{% static 'landing/img/Logo.jpg' %}" alt="logo" style="width:150px";>
			{{request.user.username}} <a href="{% url 'usuarios:logout'%}">Logout</a>
		</a> 
  </nav>
<!-- FIN TOP BAR  -->

<!-- CONTENIDO -->
<div class="grid-container">
  <!-- SIDEBAR -->
	<div class="sidebar">
		<div class="menu">
			<div class="items-menu">
				<div class="dropdown">
					  <div>
							<button class="dropbtn"><i class="material-icons icon-usuarios">supervisor_account</i> Usuarios</button>
							<div class="dropdown-content">
								<div id="usuarios-nuevo">
									<a class="nuevo" href="{% url 'administracion:new-user' %}"><i class="material-icons icon-add">add_circle_outline</i> Nuevo</a>
								</div>
								<a href="#">Clientes</a>
								<a href="#">Soporte</a>
								<a href="#">Tecnología</a>
							</div>
					  </div>
			    </div>
			</div>
			<div class="items-menu">
					<div class="dropdown">
						<div>
							<button class="dropbtn"><i class="material-icons icon-usuarios">supervisor_account</i> Clientes</button>
							<div class="dropdown-content">
								<div id="usuarios-nuevo">
									<a class="nuevo" href="#"><i class="material-icons icon-add">add_circle_outline</i> Nuevo</a>
								</div>
								<a href="#">Consulta</a>
							</div>
						</div>
					</div>
			</div>
			<div class="items-menu">
				otros....
			</div>
		</div>
	</div>
  <!-- FIN SIDEBAR -->	
	

	<div class="contenido">
		{% block content %}

		{% endblock %}
	</div>
  	
</div>
<!-- FIN CONTENIDO -->

<footer>
  <p>Grexco S.A.S.</p>
</footer>

</body>
</html>

grexco/grexco/templates/administracion/nuevo_usuario.html
{% extends './base_dashboard.html' %}

{% load static %}

{% block js-css %}
	<link rel="stylesheet" type="text/css" href="{% static 'administracion/css/nuevo_usuario.css' %}"> 
	<script src="{% static 'administracion/js/nuevo_usuario.js' %}"></script>
{% endblock %}

{% block content %}

	<div class="contenedor-nuevo-usuario">
		<h2>Nuevo usuario</h2>
		<hr>
		<div>
			<label for="">Tipo de usuario:</label>
			<select name="" id="">
				<option value="none">Seleccione un tipo de usuario</option>
				<option value="cliente">Cliente</option>
				<option value="soporte">Soporte</option>
				<option value="tecnologia">Tecnología</option>
			</select>
		</div>	
		
		<!-- Formulario nuevo usuario: Cliente -->
		<div id="form-cliente">
			<div>
				<div>
					<form action="">
						<div class="flex-row">
							
							<!-- Columna 1 -->
							<div class="flex-column">

								<!-- Item -->
								<div class="form-item">
									<label for=""><i class="asterisco">*</i> Empresa: </label>
									<span>Falta el nombre de la empresa</span>
									<input type="text" id="frm-cli-company">
								</div>

								<!-- Item -->
								<div class="form-item">
									<label for=""><i class="asterisco">*</i> Dirección: </label>
									<span>Falta la dirección</span>
									<input type="text" id="frm-cli-address">
								</div>

								<!-- Item -->
								<div class="form-item">
									<label for=""><i class="asterisco">*</i> Nombre contacto:</label>
									<span>Falta el nombre de contacto</span>
									<input type="text" name="" id="frm-cli-contact-name">
								</div>

							</div>
							<!-- Fin columna 1 -->

							<!-- Columna 2 -->
							<div class="flex-column">

								<!-- Item -->
								<div class="form-item">
									<label for=""><i class="asterisco">*</i> NIT: </label>
									<span>Falta el NIT</span>
									<input type="text" id="frm-cli-nit">
								</div>

								<!-- Item -->
								<div class="form-item">
									<label for=""><i class="asterisco">*</i> Teléfono: </label>
									<span>Falta el teléfono</span>
									<input type="text" name="" id="frm-cli-number-phone">
								</div>

								<!-- Item -->
								<div class="form-item">
									<label for=""><i class="asterisco">*</i> Correo contacto:</label><span>Falta el correo de contacto</span>
									<input type="text" name="" id="frm-cli-email">
								</div>
							</div>
							<!-- Fin columna 2 -->
						</div>

						<!-- Item -->
						<div class="form-item">
							<label for=""><i class="asterisco">*</i> Nombre usuario:</label>
							<div>
								<span>Falta el nombre de usuario</span>
								<input type="text" name="" id="frm-cli-username">@grexco.com.co
							</div>
						</div>

						<!-- Disclaimer y botón Guardar -->
						<p class="requerido"> * Campo requerido</p>
						<input id="save-user" class="btn-save" type="submit" value="Guardar">
					</form>
				</div>
			</div>
		</div>
		<!-- Fin formulario nuevo usuario: Cliente -->

		<!-- Formulario nuevo usuario: Soporte -->
		<div id="form-soporte">
			<div>
			  <form action="">
			  	<div class="flex-row">

					<!-- Columna 1 -->
					<div class="flex-column">
						
						<!-- Item -->
						<div class="form-item">
						  <label for=""><i class="asterisco">*</i> Primer nombre:</label>
						  <span>Este campo es obligatorio</span>
						  <input type="text" name="" id="frm-sop-first-name">
					    </div>
						
						<!-- Item -->
						<div class="form-item">
							<label for=""><i class="asterisco">*</i> Primer apellido:</label>
							<span>Este campo es obligatorio</span>
							<input type="text" name="" id="frm-sop-surname">
						</div>

					</div>

					<!-- Columna 2 -->
					<div class="flex-column">
						
						<!-- Item -->
						<div class="form-item">
							<label for="">Segundo nombre:</label>
							<input type="text" name="" id="frm-sop-second-name">
						</div>

						<!-- Item -->
						<div class="form-item">
							<label for="">Segundo apellido:</label>
							<input type="text" name="" id="frm-sop-second-surname">
						</div>

					</div>

					<!-- Disclaimer y botón Guardar -->
					<p class="requerido"> * Campo requerido</p>
					<input id="save-client" class="btn-save" type="submit" value="Guardar">

				</div>
			  </form>
			</div>
		</div>
		<!-- Fin formulario nuevo usuario: Soporte -->


		<div id="form-tecnologia">
			<p>Tecnología</p>
		</div>
	</div>
	
{% endblock %}